### ISSUE TITLE
Release failing but extension got updated

### ISSUE THREAD

**Issue by sebbi08** [GabrielDuarteM/semantic-release-chrome#41]
after running the task the extension got updated but the release is showing the following error in console

```
[3:33:41 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: Cannot read property '0' of undefined
    at publish (***extension/node_modules/semantic-release-chrome/dist/publish.js:60:44)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: 'semantic-release-chrome' }
{ TypeError: Cannot read property '0' of undefined
    at publish (***extension/node_modules/semantic-release-chrome/dist/publish.js:60:44)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: 'semantic-release-chrome' }
```

the this is my extension is a devtool extension with the permision 'activeTab' and therfor every release need a review maybe this has something to do with it

**Comment by davesnx** [comment]
Having the same issue:

```
[6:43:15 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Cannot read property '0' of undefined
    at publish (/home/circleci/repo/node_modules/semantic-release-chrome/dist/publish.js:60:44)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async validator (/home/circleci/repo/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/circleci/repo/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/home/circleci/repo/node_modules/p-reduce/index.js:16:18) {
  pluginName: 'semantic-release-chrome'
}
```

Do you know if there's any problem pushing versions too soon? I mean, I have a permission issue as well with my extension and I wait usually 2/3days. 
What happens with the pushed versions that are on review? 

Thanks and sorry to diverge with a random question!

**Comment by davesnx** [comment]
Thanks :D

**Comment by GabrielDuarteM** [comment]
Hi @davesnx! About your question, I'm not exactly sure, as I never experienced this but, if I were to guess, they are probably taking some time to review your extension to see if it conforms to their rules of submission, and if it does, it will be published soon...

All the best!
