### ISSUE TITLE
PUBLISHED_WITH_FRICTION_WARNING makes semantic-release-chrome fail

### ISSUE THREAD

**Issue by exKAZUu** [GabrielDuarteM/semantic-release-chrome#46]
# Issue

- [x] I have searched the [issues](https://github.com/GabrielDuarteM/semantic-release-chrome/issues) of this repository and believe that this is not a duplicate.

## Your Environment

- `semantic-release-chrome` version: https://github.com/exKAZUu/semantic-release-chrome (v1.1.1 with #44)
- `node` version: v10.16.3
- `yarn` version: 1.17.3

## What you did and problem description

When publishing my extension (https://github.com/WillBooster/plantuml-visualizer/), PUBLISHED_WITH_FRICTION_WARNING occurs and it makes `semantic-release-chrome` fail.

## What happened

Here is the log.

```
[1:55:45 PM] [semantic-release] › ℹ  Start step "publish" of plugin "semantic-release-chrome"
[1:55:54 PM] [semantic-release] › ✖  Failed step "publish" of plugin "semantic-release-chrome"
[1:55:54 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[1:55:55 PM] [semantic-release] [@semantic-release/github] › ℹ  Created issue #229: https://github.com/WillBooster/plantuml-visualizer/issues/229.
[1:55:55 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[1:55:55 PM] [semantic-release] › ✖  PUBLISHED_WITH_FRICTION_WARNING Your item needs extra time to review because your item has all hosts permission.
{ AggregateError: 
    SemanticReleaseError: Your item needs extra time to review because your item has all hosts permission.
        at publish (/home/circleci/project/node_modules/semantic-release-chrome/dist/publish.js:62:19)
    at publish (/home/circleci/project/node_modules/semantic-release-chrome/dist/publish.js:66:11)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Reproduction repository/CodeSandbox

https://github.com/WillBooster/plantuml-visualizer/

## Suggested solution

`semantic-release-chrome` should just ignore `PUBLISHED_WITH_FRICTION_WARNING` because this warning is not problematic for releasing extensions.

**Comment by GabrielDuarteM** [comment]
Hi @exKAZUu! Thank you for another PR!

I was looking for this `PUBLISHED_WITH_FRICTION_WARNING` on google, but it doesn't seem very common, mostly it pointed to another extension which had also this problem, and I couldn't find anything about that warning on the webstore api docs... It seems to be related to when the extension gets into a review process, did that happen to you as well?

If it is because of the review thing, the extension probably would not available for download right away (correct me if I'm wrong), so we should probably display a message to inform that to the user so that it doesn't get unnoticed.
